sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t sebastianalbers/rpi-gitea .
# test image
- docker run sebastianalbers/rpi-gitea /app/gitea/gitea --version
after_success:
# notify Docker Hub to make a new build
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    # trigger build on Docker Hub
    curl -X POST "$DOCKER_HUB_TRIGGER_URL"
  elif [ "$TRAVIS_TAG" != "" ]; then
    # push Docker image to Docker Hub
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    docker push "sebastianalbers/rpi-gitea:${TRAVIS_TAG}"
  fi

